### ISSUE TITLE
Extracting frame-wise features with I3D

### ISSUE THREAD

**Issue by gpmarques** [v-iashin/video_features#4] opened 2021-05-26 16:00 UTC
Hey. Is there any way to extract frame a frame features with I3D? I'd like to extract one feature vector per frame. What stack size and step size should I use to do that? Thanks!

**Comment by v-iashin** [comment] 2021-05-26 16:25
Hey. Interesting question! Have you tried to use stack and step sizes to be equal to one?

Can I ask why do you need to use a 3D Conv net on a single frame?

**Comment by gpmarques** [comment] 2021-05-26 22:03
Hey! Thanks for the quick reply. I have expressed myself badly, I actually want to extract the feature vector for every 2 frames.
Considering a video with N frames I'd like to generate the feature vector of every consecutive pair:
Frame 0 -> Frame 1
Frame 1 -> Frame 2
...
Frame N-2 -> Frame N-1

**Comment by v-iashin** [comment] 2021-05-27 08:34
Hey! Ok I see, thanks for clarifying! 

Unfortunately, I don't think it is possible. By design, I3D does not support input lengths that will result in a tensor for `avg_pool` shorter than 2 (and, thus, original input length shorter than 10)
https://github.com/v-iashin/video_features/blob/b11c2a36c0ae882c65b3d083e340244c56fa803a/models/i3d/i3d_src/i3d_net.py#L226

This means, I am afraid, you have to adapt the code on your end e.g. by using `AdaptiveAvgPool` instead of just comment that line. Check out our [documentation for ResNet frame-wise features](https://v-iashin.github.io/video_features/models/resnet/) maybe they could be useful for your project.

I will update the arg sanity test, so it will fail if user specifies `stack_size` shorter than 10.

Thanks a lot for the catch and good luck with your project. I will close this because it is not a `video_features` issue but I3D's design proposed by the authors.

**Closed by v-iashin** 2021-05-27 08:34 UTC

**Comment by gpmarques** [comment] 2021-05-27 13:57
Thanks for the explanation and suggestions!

**Comment by Charlestar** [comment] 2023-07-26 06:57
Hi! I have faced a similar problem, I find that I3D use a stack to store frames and then extract feature, when stack is not full, no feature will output.
For example, if I set stack size=16 and step size=1, I will get ’video frame num - stack size' features.
However, I want to get feature length equal to video length, is there any way to accomplish this?
I have an idea that copy the first frame of video several times to get feature at once ,but I don't know whether this makes sense.
I also want to know when stack is full, the output feature corresponds to the last frame of stack or the middle frame of stack, this will affect whether I choose to copy the first frame 'stack size' times or first and last frame of video 'stack size / 2' times.
