### ISSUE TITLE
About center crop

### ISSUE THREAD

**Issue by htowa** [v-iashin/video_features#131] opened 2024-05-02 13:52 UTC
Dear iashin

thank you for the nice feature

I3D in this video_features seems to extract features from the center of the frame image using center cropping.

https://github.com/GowthamGottimukkala/I3D_Feature_Extraction_resnet
Are there any plans to add 10 crop augmentation functionality like this person?

thank you!

**Comment by v-iashin** [comment] 2024-05-02 13:57
no, not at the moment, i'm afraid.

however, i'd love to consider a pull request implementing this (fixing or redoing the earlier attempt: #110).

I'm going to close this because it is a duplicate of #72 and #92 issue.

**Closed by v-iashin** 2024-05-02 13:57 UTC
