### ISSUE TITLE
is tencrop avaliable?

### ISSUE THREAD

**Issue by wooeagle** [v-iashin/video_features#92] opened 2023-02-21 04:44 UTC
hi! thanks for your repo, which is very useful.
i wondering about **torchvision.transforms.TenCrop** apply to your code.

i was attempt to change some code in extract_resnet.py

# class ExtraResNet in extra_resnet.py #
self.transforms = transforms.Compose([
            transforms.ToPILImage(),
            transforms.Resize(256),
            transforms.CenterCrop(224), -> **transforms.TenCrop(224),**
            transforms.ToTensor(), -> **transforms.Lambda(lambda crops: torch.stack([transforms.ToTensor()(crop) for crop in crops])),**
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]) ->
                 **transforms.Lambda(lambda normal: torch.stack([transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])(normalize) for normalize in normal]))**
        ])

but i got error as below:
 **RuntimeError: Expected 3d (unbatched) or 4d (batched) input to conv2d, but got input of size: [64, 10, 3, 224, 224]**

please let me know if you have idea. thanks!

**Comment by v-iashin** [comment] 2023-02-21 05:07
Hey,  have got a similar request already #72 

At the moment i don’t have time to implement it but i would appreciate if someone could take a look

**Comment by v-iashin** [comment] 2024-05-02 13:58
duplicate of #72

**Closed by v-iashin** 2024-05-02 13:58 UTC
Labels: enhancement
