### ISSUE TITLE
Feature Extraction Problem in RTX 3090

### ISSUE THREAD

**Issue by rabeya-akter** [v-iashin/video_features#100] opened 2023-04-08 07:36 UTC
I am trying to extract feature_type = i3d in RTX 3090. But it freezes the terminal after printing this:

feature_type: i3d
stack_size: 12
step_size: 2
streams: rgb
flow_type: pwc
extraction_fps: null
device: cuda:0
on_extraction: print
output_path: ./output/i3d
tmp_path: ./tmp/i3d
keep_tmp_files: false
show_pred: false
config: null
video_paths: null
file_with_video_paths: ./sample/sample_video_paths.txt

Device: cuda:0

and doesn't do anything after this.

**Comment by v-iashin** [comment] 2023-04-08 07:43
duplicate of #13

**Closed by v-iashin** 2023-04-08 07:43 UTC
